services:
  bl-extractor:
    build: .
    container_name: bl-extractor
    restart: unless-stopped
    volumes:
      - surya-cache:/root/.cache/datalab
    env_file:
      - .env
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      - RECOGNITION_BATCH_SIZE=8
      - DETECTOR_BATCH_SIZE=2
      - URL_GLM_SDK=http://glm-ocr-sdk:5002/parse
    ports:
      - "8500:8500"
    depends_on:
      - glm-ocr-sdk
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  glm-ocr-sdk:
    build:
      context: ./docker/glmocr
    container_name: glm-ocr-sdk
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5002:5002"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

volumes:
  surya-cache:
